name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        oc:
          - "4.1"
          - "4.2"
          - "4.3"
          - "4.4"
          - "4.5"
          - "4.6"
          - "4.7"
          - "4.8"
          - "4.9"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: "v${{ matrix.oc }}"
          file: "v${{ matrix.oc }}/Dockerfile"
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            docker.io/appuio/oc:v${{ matrix.oc }}
            quay.io/appuio/oc:v${{ matrix.oc }}
